[discord]
token = ""
gateway_version = 9
api_url = "https://discord.com/api"

[cluster]
events = [ "MESSAGE_CREATE" ]

    [cluster.shard_options]
    intents = [ "GuildMessages" ]
    decompressor = "zlib"
    encoding = "etf"
    url = "wss://gateway.discord.gg"

    [cluster.sharding]
    type = "auto"

    ## manual
    shard_total = 10
    shards = [ 5, 6, 7, 8, 9 ]
        # or to start shards [5, 6, 7, 8, 9]
        [cluster.sharding.shards]
        first_id = 5
        last_id = 9

    ## clustered
    cluster_id = 1
    shard_total = 2
    shards_per_cluster = 2

[amqp]
host = "localhost"
group = "mojuru"
subgroup = "gateway"
command_event = "command"

[redis]
host = "localhost"
port = 6379

[metrics]
enabled = false
port = 4420
endpoint = "/metrics"
